### ISSUE TITLE
Copy elements to Simulator when switching to it

### ISSUE THREAD

**Issue by 0x4d** [renew-js/renew-ui#7]
All elements from Modeler should be copied to the Simulator when `Run Simulation` is called form the menu.

**Comment by tim-kilian** [comment]
There are serval ways to archive this:

1. Use the import/export to interchange the elements
2. Find a ways to dump it, and read the dump in the simulator
3. Unload and load appropiate modules to leave the elementRegistery as it is

I think we decided to go with the first, because in the second the draw wasn't triggered after dumping it in. The thrid is also pretty complicated because of the removal from the modules. Once one is loaded, it's hard to unload it.

**Comment by 0x4d** [comment]
You are right. There are two main Problems:

1. Elements in the registry hold a reference to the SVG DOM element representing it. This reference has to be updated.
2. Elements hold object references (labels, source, target, etc.). Those are not enumerable.

Both could potentially be worked around. But for the moment I am content with using `exporter.getExport()` which is a pretty straightforward dump, leaving out DOM references and serializing object references. And then passing the result to `importer.import(data)` which deserializes the object references and then draws the elements using `canvas`.

**Comment by 0x4d** [comment]
This issue is tackled in branches [renew-ui/context-switching](/renew-js/renew-ui/tree/context-switching) and [renew-lib/context-switching](/renew-js/renew-lib/tree/context-switching).
